//
//  TMURLSessionObserver.h
//  TMTumblrSDK
//
//  Created by Kenny Ackerson on 1/6/16.
//
//

#import <Foundation/Foundation.h>
#import "TMURLSessionTaskObserver.h"

/**
 * A class that manages tasks that were generated by a URL session.
 */
__attribute__((objc_subclassing_restricted))
@interface TMURLSessionObserver : NSObject

/**
 *  Initializes an instance of @c TMURLSessionObserver.
 *
 *  @param handlers An array of blocks that can handle the status updates.
 *
 *  @return A newly intialized instance of @c TMURLSessionObserver.
 */
- (nonnull instancetype)initWithHandlers:(nonnull NSArray <TMURLSessionTaskObserverUpdateHandler> *)handlers NS_DESIGNATED_INITIALIZER;

/**
 *  Unavailable.
 *
 *  @return Undetermined.
 */
- (nonnull instancetype)init __attribute__((unavailable("Please use initWithHandlers: instead.")));

/**
 *  Adds a session task to observe.
 *
 *  @param task The task to observe.
 */
- (void)addSessionTask:(nonnull NSURLSessionTask *)task;

@end
