platform :ios, '5.0'

target 'PhotoPostExample' do
  pod 'TMTumblrSDK/APIClient', :path => '../..'
end

plugin 'cocoapods-keys', {
  :project => 'PhotoPostExample',
  :keys => [
    "OAuthConsumerKey",
    "OAuthConsumerSecret"
  ]
}
